# CMake generated Testfile for 
# Source directory: /home/ubuntu/openmind/omnn/math/test
# Build directory: /home/ubuntu/openmind/omnn/math/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(08_System "/home/ubuntu/openmind/bin/08_System")
set_tests_properties(08_System PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/08_System.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(8Q "/home/ubuntu/openmind/bin/8Q")
set_tests_properties(8Q PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/8Q.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Exponentiation_test "/home/ubuntu/openmind/bin/Exponentiation_test")
set_tests_properties(Exponentiation_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Exponentiation_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Fraction_test "/home/ubuntu/openmind/bin/Fraction_test")
set_tests_properties(Fraction_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Fraction_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Integer_test "/home/ubuntu/openmind/bin/Integer_test")
set_tests_properties(Integer_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Integer_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(ManualTest "/home/ubuntu/openmind/bin/ManualTest")
set_tests_properties(ManualTest PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/ManualTest.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Modulo_test "/home/ubuntu/openmind/bin/Modulo_test")
set_tests_properties(Modulo_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Modulo_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(MultiValues_test "/home/ubuntu/openmind/bin/MultiValues_test")
set_tests_properties(MultiValues_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/MultiValues_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Polyfit_test "/home/ubuntu/openmind/bin/Polyfit_test")
set_tests_properties(Polyfit_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Polyfit_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Product_test "/home/ubuntu/openmind/bin/Product_test")
set_tests_properties(Product_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Product_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Radicals "/home/ubuntu/openmind/bin/Radicals")
set_tests_properties(Radicals PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Radicals.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(SchoolTasks "/home/ubuntu/openmind/bin/SchoolTasks")
set_tests_properties(SchoolTasks PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SchoolTasks.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Stasis "/home/ubuntu/openmind/bin/Stasis")
set_tests_properties(Stasis PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Stasis.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(Sum_test "/home/ubuntu/openmind/bin/Sum_test")
set_tests_properties(Sum_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Sum_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(SySHA_test "/home/ubuntu/openmind/bin/SySHA_test")
set_tests_properties(SySHA_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SySHA_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(TicTacToe "/home/ubuntu/openmind/bin/TicTacToe")
set_tests_properties(TicTacToe PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/TicTacToe.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(VarHost_test "/home/ubuntu/openmind/bin/VarHost_test")
set_tests_properties(VarHost_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/VarHost_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(logic "/home/ubuntu/openmind/bin/logic")
set_tests_properties(logic PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/logic.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(sh_test "/home/ubuntu/openmind/bin/sh_test")
set_tests_properties(sh_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/sh_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
add_test(ts "/home/ubuntu/openmind/bin/ts")
set_tests_properties(ts PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/ts.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
