# CMake generated Testfile for 
# Source directory: /home/ubuntu/openmind/omnn/math/test
# Build directory: /home/ubuntu/openmind/omnn/math/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(08_System "/home/ubuntu/openmind/bin/Debug/08_System")
  set_tests_properties(08_System PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/08_System.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(08_System "/home/ubuntu/openmind/bin/Release/08_System")
  set_tests_properties(08_System PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/08_System.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(08_System "/home/ubuntu/openmind/bin/RelWithDebInfo/08_System")
  set_tests_properties(08_System PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/08_System.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(08_System NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(8Q "/home/ubuntu/openmind/bin/Debug/8Q")
  set_tests_properties(8Q PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/8Q.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(8Q "/home/ubuntu/openmind/bin/Release/8Q")
  set_tests_properties(8Q PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/8Q.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(8Q "/home/ubuntu/openmind/bin/RelWithDebInfo/8Q")
  set_tests_properties(8Q PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/8Q.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(8Q NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Exponentiation_test "/home/ubuntu/openmind/bin/Debug/Exponentiation_test")
  set_tests_properties(Exponentiation_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Exponentiation_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Exponentiation_test "/home/ubuntu/openmind/bin/Release/Exponentiation_test")
  set_tests_properties(Exponentiation_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Exponentiation_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Exponentiation_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Exponentiation_test")
  set_tests_properties(Exponentiation_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Exponentiation_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Exponentiation_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Fraction_test "/home/ubuntu/openmind/bin/Debug/Fraction_test")
  set_tests_properties(Fraction_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Fraction_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Fraction_test "/home/ubuntu/openmind/bin/Release/Fraction_test")
  set_tests_properties(Fraction_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Fraction_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Fraction_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Fraction_test")
  set_tests_properties(Fraction_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Fraction_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Fraction_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Integer_test "/home/ubuntu/openmind/bin/Debug/Integer_test")
  set_tests_properties(Integer_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Integer_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Integer_test "/home/ubuntu/openmind/bin/Release/Integer_test")
  set_tests_properties(Integer_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Integer_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Integer_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Integer_test")
  set_tests_properties(Integer_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Integer_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Integer_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Modulo_test "/home/ubuntu/openmind/bin/Debug/Modulo_test")
  set_tests_properties(Modulo_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Modulo_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Modulo_test "/home/ubuntu/openmind/bin/Release/Modulo_test")
  set_tests_properties(Modulo_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Modulo_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Modulo_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Modulo_test")
  set_tests_properties(Modulo_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Modulo_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Modulo_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(MultiValues_test "/home/ubuntu/openmind/bin/Debug/MultiValues_test")
  set_tests_properties(MultiValues_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/MultiValues_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(MultiValues_test "/home/ubuntu/openmind/bin/Release/MultiValues_test")
  set_tests_properties(MultiValues_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/MultiValues_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(MultiValues_test "/home/ubuntu/openmind/bin/RelWithDebInfo/MultiValues_test")
  set_tests_properties(MultiValues_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/MultiValues_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(MultiValues_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Polyfit_test "/home/ubuntu/openmind/bin/Debug/Polyfit_test")
  set_tests_properties(Polyfit_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Polyfit_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Polyfit_test "/home/ubuntu/openmind/bin/Release/Polyfit_test")
  set_tests_properties(Polyfit_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Polyfit_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Polyfit_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Polyfit_test")
  set_tests_properties(Polyfit_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Polyfit_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Polyfit_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Product_test "/home/ubuntu/openmind/bin/Debug/Product_test")
  set_tests_properties(Product_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Product_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Product_test "/home/ubuntu/openmind/bin/Release/Product_test")
  set_tests_properties(Product_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Product_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Product_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Product_test")
  set_tests_properties(Product_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Product_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Product_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Radicals "/home/ubuntu/openmind/bin/Debug/Radicals")
  set_tests_properties(Radicals PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Radicals.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Radicals "/home/ubuntu/openmind/bin/Release/Radicals")
  set_tests_properties(Radicals PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Radicals.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Radicals "/home/ubuntu/openmind/bin/RelWithDebInfo/Radicals")
  set_tests_properties(Radicals PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Radicals.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Radicals NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SchoolTasks "/home/ubuntu/openmind/bin/Debug/SchoolTasks")
  set_tests_properties(SchoolTasks PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SchoolTasks.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SchoolTasks "/home/ubuntu/openmind/bin/Release/SchoolTasks")
  set_tests_properties(SchoolTasks PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SchoolTasks.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SchoolTasks "/home/ubuntu/openmind/bin/RelWithDebInfo/SchoolTasks")
  set_tests_properties(SchoolTasks PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SchoolTasks.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(SchoolTasks NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Stasis "/home/ubuntu/openmind/bin/Debug/Stasis")
  set_tests_properties(Stasis PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Stasis.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Stasis "/home/ubuntu/openmind/bin/Release/Stasis")
  set_tests_properties(Stasis PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Stasis.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Stasis "/home/ubuntu/openmind/bin/RelWithDebInfo/Stasis")
  set_tests_properties(Stasis PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Stasis.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Stasis NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Sum_test "/home/ubuntu/openmind/bin/Debug/Sum_test")
  set_tests_properties(Sum_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Sum_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Sum_test "/home/ubuntu/openmind/bin/Release/Sum_test")
  set_tests_properties(Sum_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Sum_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Sum_test "/home/ubuntu/openmind/bin/RelWithDebInfo/Sum_test")
  set_tests_properties(Sum_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/Sum_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(Sum_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SySHA_test "/home/ubuntu/openmind/bin/Debug/SySHA_test")
  set_tests_properties(SySHA_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SySHA_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SySHA_test "/home/ubuntu/openmind/bin/Release/SySHA_test")
  set_tests_properties(SySHA_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SySHA_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SySHA_test "/home/ubuntu/openmind/bin/RelWithDebInfo/SySHA_test")
  set_tests_properties(SySHA_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/SySHA_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(SySHA_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TicTacToe "/home/ubuntu/openmind/bin/Debug/TicTacToe")
  set_tests_properties(TicTacToe PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/TicTacToe.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TicTacToe "/home/ubuntu/openmind/bin/Release/TicTacToe")
  set_tests_properties(TicTacToe PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/TicTacToe.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TicTacToe "/home/ubuntu/openmind/bin/RelWithDebInfo/TicTacToe")
  set_tests_properties(TicTacToe PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/TicTacToe.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(TicTacToe NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(VarHost_test "/home/ubuntu/openmind/bin/Debug/VarHost_test")
  set_tests_properties(VarHost_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/VarHost_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(VarHost_test "/home/ubuntu/openmind/bin/Release/VarHost_test")
  set_tests_properties(VarHost_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/VarHost_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(VarHost_test "/home/ubuntu/openmind/bin/RelWithDebInfo/VarHost_test")
  set_tests_properties(VarHost_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/VarHost_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(VarHost_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logic "/home/ubuntu/openmind/bin/Debug/logic")
  set_tests_properties(logic PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/logic.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logic "/home/ubuntu/openmind/bin/Release/logic")
  set_tests_properties(logic PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/logic.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logic "/home/ubuntu/openmind/bin/RelWithDebInfo/logic")
  set_tests_properties(logic PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/logic.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(logic NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(sh_test "/home/ubuntu/openmind/bin/Debug/sh_test")
  set_tests_properties(sh_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/sh_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(sh_test "/home/ubuntu/openmind/bin/Release/sh_test")
  set_tests_properties(sh_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/sh_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(sh_test "/home/ubuntu/openmind/bin/RelWithDebInfo/sh_test")
  set_tests_properties(sh_test PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/sh_test.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(sh_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ts "/home/ubuntu/openmind/bin/Debug/ts")
  set_tests_properties(ts PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/ts.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ts "/home/ubuntu/openmind/bin/Release/ts")
  set_tests_properties(ts PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/ts.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ts "/home/ubuntu/openmind/bin/RelWithDebInfo/ts")
  set_tests_properties(ts PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/openmind/omnn/math/test/ts.db" _BACKTRACE_TRIPLES "/home/ubuntu/openmind/cmake/bins.cmake;308;add_test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;1;test;/home/ubuntu/openmind/omnn/math/test/CMakeLists.txt;0;")
else()
  add_test(ts NOT_AVAILABLE)
endif()
