extends: relaxed

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['TRUE', 'True', 'true', 'FALSE', 'False', 'false', 'YES', 'Yes', 'yes', 'NO', 'No', 'no', 'ON', 'On', 'on', 'OFF', 'Off', 'off']
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
  document-start: disable
  trailing-spaces: disable
  empty-lines: disable
  new-line-at-end-of-file: disable
  comments-indentation: disable
