# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/openmind

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/openmind

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/openmind/CMakeFiles /home/ubuntu/openmind//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/openmind/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prerequisites

# Build rule for target.
prerequisites: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prerequisites
.PHONY : prerequisites

# fast build rule for target.
prerequisites/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prerequisites.dir/build.make CMakeFiles/prerequisites.dir/build
.PHONY : prerequisites/fast

#=============================================================================
# Target rules for targets named git-gui

# Build rule for target.
git-gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 git-gui
.PHONY : git-gui

# fast build rule for target.
git-gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git-gui.dir/build.make CMakeFiles/git-gui.dir/build
.PHONY : git-gui/fast

#=============================================================================
# Target rules for targets named rebase-main

# Build rule for target.
rebase-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebase-main
.PHONY : rebase-main

# fast build rule for target.
rebase-main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rebase-main.dir/build.make CMakeFiles/rebase-main.dir/build
.PHONY : rebase-main/fast

#=============================================================================
# Target rules for targets named rebase-main-interactive

# Build rule for target.
rebase-main-interactive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebase-main-interactive
.PHONY : rebase-main-interactive

# fast build rule for target.
rebase-main-interactive/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rebase-main-interactive.dir/build.make CMakeFiles/rebase-main-interactive.dir/build
.PHONY : rebase-main-interactive/fast

#=============================================================================
# Target rules for targets named update

# Build rule for target.
update: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update
.PHONY : update

# fast build rule for target.
update/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/update.dir/build.make CMakeFiles/update.dir/build
.PHONY : update/fast

#=============================================================================
# Target rules for targets named push-to-develop

# Build rule for target.
push-to-develop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 push-to-develop
.PHONY : push-to-develop

# fast build rule for target.
push-to-develop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push-to-develop.dir/build.make CMakeFiles/push-to-develop.dir/build
.PHONY : push-to-develop/fast

#=============================================================================
# Target rules for targets named force-push-head-to-develop

# Build rule for target.
force-push-head-to-develop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 force-push-head-to-develop
.PHONY : force-push-head-to-develop

# fast build rule for target.
force-push-head-to-develop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/force-push-head-to-develop.dir/build.make CMakeFiles/force-push-head-to-develop.dir/build
.PHONY : force-push-head-to-develop/fast

#=============================================================================
# Target rules for targets named force-push-head1-to-develop

# Build rule for target.
force-push-head1-to-develop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 force-push-head1-to-develop
.PHONY : force-push-head1-to-develop

# fast build rule for target.
force-push-head1-to-develop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/force-push-head1-to-develop.dir/build.make CMakeFiles/force-push-head1-to-develop.dir/build
.PHONY : force-push-head1-to-develop/fast

#=============================================================================
# Target rules for targets named boost

# Build rule for target.
boost: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost
.PHONY : boost

# fast build rule for target.
boost/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost.dir/build.make CMakeFiles/boost.dir/build
.PHONY : boost/fast

#=============================================================================
# Target rules for targets named disable_openmind_tests

# Build rule for target.
disable_openmind_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disable_openmind_tests
.PHONY : disable_openmind_tests

# fast build rule for target.
disable_openmind_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disable_openmind_tests.dir/build.make CMakeFiles/disable_openmind_tests.dir/build
.PHONY : disable_openmind_tests/fast

#=============================================================================
# Target rules for targets named rt

# Build rule for target.
rt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt
.PHONY : rt

# fast build rule for target.
rt/fast:
	$(MAKE) $(MAKESILENT) -f omnn/rt/CMakeFiles/rt.dir/build.make omnn/rt/CMakeFiles/rt.dir/build
.PHONY : rt/fast

#=============================================================================
# Target rules for targets named fastest_get

# Build rule for target.
fastest_get: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastest_get
.PHONY : fastest_get

# fast build rule for target.
fastest_get/fast:
	$(MAKE) $(MAKESILENT) -f omnn/rt/tests/CMakeFiles/fastest_get.dir/build.make omnn/rt/tests/CMakeFiles/fastest_get.dir/build
.PHONY : fastest_get/fast

#=============================================================================
# Target rules for targets named storage

# Build rule for target.
storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage
.PHONY : storage

# fast build rule for target.
storage/fast:
	$(MAKE) $(MAKESILENT) -f omnn/storage/CMakeFiles/storage.dir/build.make omnn/storage/CMakeFiles/storage.dir/build
.PHONY : storage/fast

#=============================================================================
# Target rules for targets named LevelDbStorage

# Build rule for target.
LevelDbStorage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LevelDbStorage
.PHONY : LevelDbStorage

# fast build rule for target.
LevelDbStorage/fast:
	$(MAKE) $(MAKESILENT) -f omnn/storage/tests/CMakeFiles/LevelDbStorage.dir/build.make omnn/storage/tests/CMakeFiles/LevelDbStorage.dir/build
.PHONY : LevelDbStorage/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/CMakeFiles/math.dir/build.make omnn/math/CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named 08_System

# Build rule for target.
08_System: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 08_System
.PHONY : 08_System

# fast build rule for target.
08_System/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/08_System.dir/build.make omnn/math/test/CMakeFiles/08_System.dir/build
.PHONY : 08_System/fast

#=============================================================================
# Target rules for targets named 8Q

# Build rule for target.
8Q: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 8Q
.PHONY : 8Q

# fast build rule for target.
8Q/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/8Q.dir/build.make omnn/math/test/CMakeFiles/8Q.dir/build
.PHONY : 8Q/fast

#=============================================================================
# Target rules for targets named Exponentiation_test

# Build rule for target.
Exponentiation_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Exponentiation_test
.PHONY : Exponentiation_test

# fast build rule for target.
Exponentiation_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Exponentiation_test.dir/build.make omnn/math/test/CMakeFiles/Exponentiation_test.dir/build
.PHONY : Exponentiation_test/fast

#=============================================================================
# Target rules for targets named Fraction_test

# Build rule for target.
Fraction_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fraction_test
.PHONY : Fraction_test

# fast build rule for target.
Fraction_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Fraction_test.dir/build.make omnn/math/test/CMakeFiles/Fraction_test.dir/build
.PHONY : Fraction_test/fast

#=============================================================================
# Target rules for targets named Integer_test

# Build rule for target.
Integer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Integer_test
.PHONY : Integer_test

# fast build rule for target.
Integer_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Integer_test.dir/build.make omnn/math/test/CMakeFiles/Integer_test.dir/build
.PHONY : Integer_test/fast

#=============================================================================
# Target rules for targets named ManualTest

# Build rule for target.
ManualTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ManualTest
.PHONY : ManualTest

# fast build rule for target.
ManualTest/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/ManualTest.dir/build.make omnn/math/test/CMakeFiles/ManualTest.dir/build
.PHONY : ManualTest/fast

#=============================================================================
# Target rules for targets named Modulo_test

# Build rule for target.
Modulo_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Modulo_test
.PHONY : Modulo_test

# fast build rule for target.
Modulo_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Modulo_test.dir/build.make omnn/math/test/CMakeFiles/Modulo_test.dir/build
.PHONY : Modulo_test/fast

#=============================================================================
# Target rules for targets named MultiValues_test

# Build rule for target.
MultiValues_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultiValues_test
.PHONY : MultiValues_test

# fast build rule for target.
MultiValues_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/MultiValues_test.dir/build.make omnn/math/test/CMakeFiles/MultiValues_test.dir/build
.PHONY : MultiValues_test/fast

#=============================================================================
# Target rules for targets named Polyfit_test

# Build rule for target.
Polyfit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Polyfit_test
.PHONY : Polyfit_test

# fast build rule for target.
Polyfit_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Polyfit_test.dir/build.make omnn/math/test/CMakeFiles/Polyfit_test.dir/build
.PHONY : Polyfit_test/fast

#=============================================================================
# Target rules for targets named Product_test

# Build rule for target.
Product_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Product_test
.PHONY : Product_test

# fast build rule for target.
Product_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Product_test.dir/build.make omnn/math/test/CMakeFiles/Product_test.dir/build
.PHONY : Product_test/fast

#=============================================================================
# Target rules for targets named Radicals

# Build rule for target.
Radicals: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Radicals
.PHONY : Radicals

# fast build rule for target.
Radicals/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Radicals.dir/build.make omnn/math/test/CMakeFiles/Radicals.dir/build
.PHONY : Radicals/fast

#=============================================================================
# Target rules for targets named SchoolTasks

# Build rule for target.
SchoolTasks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SchoolTasks
.PHONY : SchoolTasks

# fast build rule for target.
SchoolTasks/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/SchoolTasks.dir/build.make omnn/math/test/CMakeFiles/SchoolTasks.dir/build
.PHONY : SchoolTasks/fast

#=============================================================================
# Target rules for targets named Stasis

# Build rule for target.
Stasis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Stasis
.PHONY : Stasis

# fast build rule for target.
Stasis/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Stasis.dir/build.make omnn/math/test/CMakeFiles/Stasis.dir/build
.PHONY : Stasis/fast

#=============================================================================
# Target rules for targets named Sum_test

# Build rule for target.
Sum_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sum_test
.PHONY : Sum_test

# fast build rule for target.
Sum_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/Sum_test.dir/build.make omnn/math/test/CMakeFiles/Sum_test.dir/build
.PHONY : Sum_test/fast

#=============================================================================
# Target rules for targets named SySHA_test

# Build rule for target.
SySHA_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SySHA_test
.PHONY : SySHA_test

# fast build rule for target.
SySHA_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/SySHA_test.dir/build.make omnn/math/test/CMakeFiles/SySHA_test.dir/build
.PHONY : SySHA_test/fast

#=============================================================================
# Target rules for targets named TicTacToe

# Build rule for target.
TicTacToe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TicTacToe
.PHONY : TicTacToe

# fast build rule for target.
TicTacToe/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/TicTacToe.dir/build.make omnn/math/test/CMakeFiles/TicTacToe.dir/build
.PHONY : TicTacToe/fast

#=============================================================================
# Target rules for targets named VarHost_test

# Build rule for target.
VarHost_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VarHost_test
.PHONY : VarHost_test

# fast build rule for target.
VarHost_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/VarHost_test.dir/build.make omnn/math/test/CMakeFiles/VarHost_test.dir/build
.PHONY : VarHost_test/fast

#=============================================================================
# Target rules for targets named logic

# Build rule for target.
logic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logic
.PHONY : logic

# fast build rule for target.
logic/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/logic.dir/build.make omnn/math/test/CMakeFiles/logic.dir/build
.PHONY : logic/fast

#=============================================================================
# Target rules for targets named sh_test

# Build rule for target.
sh_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sh_test
.PHONY : sh_test

# fast build rule for target.
sh_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/sh_test.dir/build.make omnn/math/test/CMakeFiles/sh_test.dir/build
.PHONY : sh_test/fast

#=============================================================================
# Target rules for targets named ts

# Build rule for target.
ts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ts
.PHONY : ts

# fast build rule for target.
ts/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/ts.dir/build.make omnn/math/test/CMakeFiles/ts.dir/build
.PHONY : ts/fast

#=============================================================================
# Target rules for targets named ct

# Build rule for target.
ct: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ct
.PHONY : ct

# fast build rule for target.
ct/fast:
	$(MAKE) $(MAKESILENT) -f omnn/ct/CMakeFiles/ct.dir/build.make omnn/ct/CMakeFiles/ct.dir/build
.PHONY : ct/fast

#=============================================================================
# Target rules for targets named extrapolator

# Build rule for target.
extrapolator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extrapolator
.PHONY : extrapolator

# fast build rule for target.
extrapolator/fast:
	$(MAKE) $(MAKESILENT) -f omnn/extrapolator/CMakeFiles/extrapolator.dir/build.make omnn/extrapolator/CMakeFiles/extrapolator.dir/build
.PHONY : extrapolator/fast

#=============================================================================
# Target rules for targets named image_codec_test

# Build rule for target.
image_codec_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_codec_test
.PHONY : image_codec_test

# fast build rule for target.
image_codec_test/fast:
	$(MAKE) $(MAKESILENT) -f omnn/extrapolator/test/CMakeFiles/image_codec_test.dir/build.make omnn/extrapolator/test/CMakeFiles/image_codec_test.dir/build
.PHONY : image_codec_test/fast

#=============================================================================
# Target rules for targets named test_extrapolator

# Build rule for target.
test_extrapolator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_extrapolator
.PHONY : test_extrapolator

# fast build rule for target.
test_extrapolator/fast:
	$(MAKE) $(MAKESILENT) -f omnn/extrapolator/test/CMakeFiles/test_extrapolator.dir/build.make omnn/extrapolator/test/CMakeFiles/test_extrapolator.dir/build
.PHONY : test_extrapolator/fast

#=============================================================================
# Target rules for targets named logic1

# Build rule for target.
logic1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logic1
.PHONY : logic1

# fast build rule for target.
logic1/fast:
	$(MAKE) $(MAKESILENT) -f omnn/logic/CMakeFiles/logic1.dir/build.make omnn/logic/CMakeFiles/logic1.dir/build
.PHONY : logic1/fast

#=============================================================================
# Target rules for targets named OpenMind

# Build rule for target.
OpenMind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenMind
.PHONY : OpenMind

# fast build rule for target.
OpenMind/fast:
	$(MAKE) $(MAKESILENT) -f OpenMind/CMakeFiles/OpenMind.dir/build.make OpenMind/CMakeFiles/OpenMind.dir/build
.PHONY : OpenMind/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... boost"
	@echo "... disable_openmind_tests"
	@echo "... force-push-head-to-develop"
	@echo "... force-push-head1-to-develop"
	@echo "... git-gui"
	@echo "... prerequisites"
	@echo "... push-to-develop"
	@echo "... rebase-main"
	@echo "... rebase-main-interactive"
	@echo "... update"
	@echo "... 08_System"
	@echo "... 8Q"
	@echo "... Exponentiation_test"
	@echo "... Fraction_test"
	@echo "... Integer_test"
	@echo "... LevelDbStorage"
	@echo "... ManualTest"
	@echo "... Modulo_test"
	@echo "... MultiValues_test"
	@echo "... OpenMind"
	@echo "... Polyfit_test"
	@echo "... Product_test"
	@echo "... Radicals"
	@echo "... SchoolTasks"
	@echo "... Stasis"
	@echo "... Sum_test"
	@echo "... SySHA_test"
	@echo "... TicTacToe"
	@echo "... VarHost_test"
	@echo "... ct"
	@echo "... extrapolator"
	@echo "... fastest_get"
	@echo "... image_codec_test"
	@echo "... logic"
	@echo "... logic1"
	@echo "... math"
	@echo "... rt"
	@echo "... sh_test"
	@echo "... storage"
	@echo "... test_extrapolator"
	@echo "... ts"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

