# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/openmind

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/openmind

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/openmind/CMakeFiles /home/ubuntu/openmind//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/openmind/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prerequisites

# Build rule for target.
prerequisites: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prerequisites
.PHONY : prerequisites

# fast build rule for target.
prerequisites/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prerequisites.dir/build.make CMakeFiles/prerequisites.dir/build
.PHONY : prerequisites/fast

#=============================================================================
# Target rules for targets named disable_openmind_tests

# Build rule for target.
disable_openmind_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disable_openmind_tests
.PHONY : disable_openmind_tests

# fast build rule for target.
disable_openmind_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disable_openmind_tests.dir/build.make CMakeFiles/disable_openmind_tests.dir/build
.PHONY : disable_openmind_tests/fast

#=============================================================================
# Target rules for targets named rt

# Build rule for target.
rt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt
.PHONY : rt

# fast build rule for target.
rt/fast:
	$(MAKE) $(MAKESILENT) -f omnn/rt/CMakeFiles/rt.dir/build.make omnn/rt/CMakeFiles/rt.dir/build
.PHONY : rt/fast

#=============================================================================
# Target rules for targets named storage

# Build rule for target.
storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage
.PHONY : storage

# fast build rule for target.
storage/fast:
	$(MAKE) $(MAKESILENT) -f omnn/storage/CMakeFiles/storage.dir/build.make omnn/storage/CMakeFiles/storage.dir/build
.PHONY : storage/fast

#=============================================================================
# Target rules for targets named LevelDbStorage

# Build rule for target.
LevelDbStorage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LevelDbStorage
.PHONY : LevelDbStorage

# fast build rule for target.
LevelDbStorage/fast:
	$(MAKE) $(MAKESILENT) -f omnn/storage/tests/CMakeFiles/LevelDbStorage.dir/build.make omnn/storage/tests/CMakeFiles/LevelDbStorage.dir/build
.PHONY : LevelDbStorage/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/CMakeFiles/math.dir/build.make omnn/math/CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named math_tests

# Build rule for target.
math_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math_tests
.PHONY : math_tests

# fast build rule for target.
math_tests/fast:
	$(MAKE) $(MAKESILENT) -f omnn/math/test/CMakeFiles/math_tests.dir/build.make omnn/math/test/CMakeFiles/math_tests.dir/build
.PHONY : math_tests/fast

#=============================================================================
# Target rules for targets named ct

# Build rule for target.
ct: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ct
.PHONY : ct

# fast build rule for target.
ct/fast:
	$(MAKE) $(MAKESILENT) -f omnn/ct/CMakeFiles/ct.dir/build.make omnn/ct/CMakeFiles/ct.dir/build
.PHONY : ct/fast

#=============================================================================
# Target rules for targets named extrapolator

# Build rule for target.
extrapolator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extrapolator
.PHONY : extrapolator

# fast build rule for target.
extrapolator/fast:
	$(MAKE) $(MAKESILENT) -f omnn/extrapolator/CMakeFiles/extrapolator.dir/build.make omnn/extrapolator/CMakeFiles/extrapolator.dir/build
.PHONY : extrapolator/fast

#=============================================================================
# Target rules for targets named logic

# Build rule for target.
logic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logic
.PHONY : logic

# fast build rule for target.
logic/fast:
	$(MAKE) $(MAKESILENT) -f omnn/logic/CMakeFiles/logic.dir/build.make omnn/logic/CMakeFiles/logic.dir/build
.PHONY : logic/fast

#=============================================================================
# Target rules for targets named OpenMind

# Build rule for target.
OpenMind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenMind
.PHONY : OpenMind

# fast build rule for target.
OpenMind/fast:
	$(MAKE) $(MAKESILENT) -f OpenMind/CMakeFiles/OpenMind.dir/build.make OpenMind/CMakeFiles/OpenMind.dir/build
.PHONY : OpenMind/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... disable_openmind_tests"
	@echo "... prerequisites"
	@echo "... LevelDbStorage"
	@echo "... OpenMind"
	@echo "... ct"
	@echo "... extrapolator"
	@echo "... logic"
	@echo "... math"
	@echo "... math_tests"
	@echo "... rt"
	@echo "... storage"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

