#pragma once
#include <omnn/rt/custom_allocator.hpp>

#ifdef BOOST_UBLAS_TYPE_CHECK
#	undef BOOST_UBLAS_TYPE_CHECK
#endif
#define BOOST_UBLAS_TYPE_CHECK 0
#ifndef _USE_MATH_DEFINES
#	define _USE_MATH_DEFINES
#endif

#include <iomanip>
#include <stdexcept>
#include <limits>
#include <numeric>
#include <vector>

#include <boost/algorithm/string/replace.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/lu.hpp>

/*
	Finds the coefficients of a polynomial p(x) of degree n that fits the data,
	p(x(i)) to y(i), in a least squares sense. The result p is a row vector of
	length n+1 containing the polynomial coefficients in incremental powers.

	param:
 oX				x axis values
 oY				y axis values
 nDegree		polynomial degree including the constant

	return:
 coefficients of a polynomial starting at the constant coefficient and
 ending with the coefficient of power to nDegree.

 */
template<typename T>
auto polyfit( const std::vector<T>& oX, const std::vector<T>& oY, size_t nDegree )
{
    using namespace boost::numeric::ublas;

    if ( oX.size() != oY.size() )
        throw std::invalid_argument( "X and Y vector sizes do not match" );

    // more intuitive this way
    nDegree++;

    auto nCount =  oX.size();
    matrix<T> oXMatrix( nCount, nDegree );
    matrix<T> oYMatrix( nCount, 1 );

    // copy y matrix
    for ( size_t i = 0; i < nCount; i++ )
    {
        new (&oYMatrix(i, 0)) T(oY[i]);
    }

    // create the X matrix
    for ( size_t nRow = 0; nRow < nCount; nRow++ )
    {
        T nVal = 1.0f;
        for (size_t nCol = 0; nCol < nDegree; nCol++)
        {
            new (&oXMatrix(nRow, nCol)) T(nVal);
            nVal *= oX[nRow];
        }
    }

    // Remove debug output statements
    // std::cerr << "Input oX: ";
    // for (const auto& val : oX) std::cerr << val << " ";
    // std::cerr << std::endl;

    // std::cerr << "Input oY: ";
    // for (const auto& val : oY) std::cerr << val << " ";
    // std::cerr << std::endl;

    // std::cerr << "oXMatrix: " << oXMatrix << std::endl;
    // std::cerr << "oYMatrix: " << oYMatrix << std::endl;
    // transpose X matrix
    matrix<T> oXtMatrix( trans(oXMatrix) );
    // std::cerr << "oXtMatrix: " << oXtMatrix << std::endl;

    // multiply transposed X matrix with X matrix
    matrix<T> oXtXMatrix( prec_prod(oXtMatrix, oXMatrix) );
    // std::cerr << "oXtXMatrix: " << oXtXMatrix << std::endl;

    // multiply transposed X matrix with Y matrix
    matrix<T> oXtYMatrix( prec_prod(oXtMatrix, oYMatrix) );
// std::cerr << "oXtYMatrix: " << oXtYMatrix << std::endl;
    // lu decomposition
    permutation_matrix<int> pert(oXtXMatrix.size1());
    auto singular = lu_factorize(oXtXMatrix, pert);
    if (singular != 0) {
        // std::cerr << "Matrix is singular and cannot be inverted. oXtXMatrix: " << oXtXMatrix << std::endl;
        throw std::runtime_error("Matrix is singular and cannot be inverted");
    }
    // backsubstitution
    lu_substitute(oXtXMatrix, pert, oXtYMatrix);

    // std::cerr << "Backsubstitution result: oXtYMatrix: " << oXtYMatrix << std::endl;
    // copy the result to coeff
    return std::vector<T>( oXtYMatrix.data().begin(), oXtYMatrix.data().end() );
}

/*
	Calculates the value of a polynomial of degree n evaluated at x. The input
	argument pCoeff is a vector of length n+1 whose elements are the coefficients
	in incremental powers of the polynomial to be evaluated.

	param:
 oCoeff			polynomial coefficients generated by polyfit() function
 oX				x axis values

	return:
 Fitted Y values.
 */
template<typename T>
auto polyval( const std::vector<T>& oCoeff, const std::vector<T>& oX )
{
    auto nCount =  oX.size();
    auto nDegree = oCoeff.size();
    std::vector<T>	oY( nCount );

    for ( size_t i = 0; i < nCount; i++ )
    {
        T nY = 0;
        T nXT = 1;
        T nX = oX[i];
        for ( size_t j = 0; j < nDegree; j++ )
        {
            // multiply current x by a coefficient
            nY += oCoeff[j] * nXT;
            // power up the X
            nXT *= nX;
        }
        oY[i] = std::move(nY);
    }

    return oY;
}


template <class T>
std::string polystr(const std::vector<T>& coeff)
{
    int p = 0;
    std::stringstream s;
    s << std::setprecision(100) << 0;
    for (auto& c: coeff) {
        s << '+';
        s << '(' << c << ')';
        s << "*x^" << p++;
    }
    return boost::replace_all_copy(s.str(), "e", "*10^");
}
