
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(address_model 64 CACHE STRING "address_model" FORCE)
else()
	set(address_model 32 CACHE STRING "address_model" FORCE)
endif()

if(NOT PKG_CONFIG_FOUND)
	find_package(PkgConfig)
	option(OPENMIND_USE_PKG_CONFIG_DEPS "Use pkg-config dependencies"
		# ${PKG_CONFIG_FOUND}) # bug in pkg_check_modules macro: no REQUIRED keyword still leads to fatal error if package not found
		NO)
	if(PKG_CONFIG_FOUND)
		message("pkg-config may be used to detect some of dependencies")
	endif()
endif()

function(get_local_drives LOCAL_DRIVES)
	if(WIN32)
		execute_process(
			COMMAND fsutil fsinfo drives
			OUTPUT_VARIABLE local_drives_raw
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)

		string(REGEX MATCH "( [A-Z]:)+" local_drives_list "${local_drives_raw}")
		string(REPLACE "Drives: " "" local_drives_list "${local_drives_raw}")
		string(REPLACE " " ";" drives "${local_drives_list}")
		set(${LOCAL_DRIVES} ${drives} PARENT_SCOPE)
	endif()
endfunction()

macro(find_pkg)
	set(hint_paths
		${CMAKE_BINARY_DIR}
		${CMAKE_BINARY_DIR}/lib
		${CMAKE_BINARY_DIR}/lib64
		${CMAKE_INSTALL_PREFIX}
		)
	foreach(dep ${ARGN})
		if(NOT ${dep}_FOUND)
			if(${dep}_VERSION)
				find_package(${dep} ${${dep}_VERSION})
				if(${dep}_FOUND)
					message("find_package(${dep} ${${dep}_VERSION} REQUIRED)")
					find_package(${dep} ${${dep}_VERSION} REQUIRED)
				endif()
			elseif(${dep}_TAG AND NOT ${dep}_TAG STREQUAL HEAD)
				find_package(${dep} ${${dep}_TAG})
				if(${dep}_FOUND)
					message("find_package(${dep} ${${dep}_TAG} REQUIRED)")
					find_package(${dep} ${${dep}_TAG} REQUIRED)
				endif()
			else()
				message("find_package(${dep})")
				find_package(${dep})
			endif()
		endif()
		if(NOT ${dep}_FOUND AND OPENMIND_USE_PKG_CONFIG_DEPS)
			pkg_get_variable(PKG_${dep}_LIBRARY_DIR ${dep} libdir)
			if(EXISTS PKG_${dep}_LIBRARY_DIR)
				set(hints ${hint_paths} ${PKG_${dep}_LIBRARY_DIR})
				pkg_get_variable(${dep}_INCLUDE_DIR ${dep} includedir)
			endif()
		endif()

		if(NOT ${dep}_FOUND)
			set(hints ${hint_paths}
				${CMAKE_BINARY_DIR}/lib/${dep}
				${CMAKE_BINARY_DIR}/lib64/${dep}
				)
			if(WIN32)
				get_local_drives(drives)
				foreach(drive ${drives})
					if(EXISTS "${drive}/${dep}")
						set(hints ${hints} "${drive}/${dep}")
					endif()
					if(EXISTS "${drive}/${dep}${address_model}")
						set(hints ${hints} "${drive}/${dep}${address_model}")
					endif()
					if(EXISTS "$ENV{ProgramFiles}/${dep}")
						set(hints ${hints} "$ENV{ProgramFiles}/${dep}")
					endif()
				endforeach()
			else()
				if(EXISTS /opt/${dep})
					set(hints ${hints} "/opt/${dep}")
				endif()
			endif()
			find_package(${dep} HINTS ${hints})
		endif()

		if(NOT ${dep}_FOUND)
			find_library(${dep}_LIBRARIES
				NAMES ${dep}.framework ${dep} lib${dep} ${dep}lib lib${dep}lib
				HINTS ${hints}
				)
			if(${dep}_LIBRARIES AND EXISTS ${${dep}_LIBRARIES})
				message("${dep}_LIBRARIES: ${${dep}_LIBRARIES} with HINTS ${hints}")
				set(${dep}_FOUND ON)
			endif()
		endif()

		message("${dep}_FOUND:${${dep}_FOUND} with HINTS ${hints}")
		if(${dep}_FOUND)
			if(${dep}_LIBRARY OR ${dep}_LIBRARIES OR ${dep}_INCLUDE_DIR OR ${dep}_INCLUDE_DIRS)
				break()
			elseif(TARGET ${dep}::${dep}-static)
				set(${dep}_LIBRARY ${dep}::${dep}-static)
			elseif(TARGET ${dep}::${dep})
				set(${dep}_LIBRARY ${dep}::${dep})
			else()
				unset(${dep}_FOUND)
				continue()
			endif()
			break()
		endif()

	endforeach()
endmacro()

macro(find_local_dep)
	message("find local dep: ${ARGN}")
	if(${ARGN} MATCHES " ")
		string(REPLACE " " ";" ARGN ${ARGN})
	endif()
	foreach(dep ${ARGN})
		set(libless "")
		if(dep MATCHES "^[Ll][Ii][Bb]")
			STRING(REGEX REPLACE "^[Ll][Ii][Bb]" "" libless ${dep})
			if(NOT ${dep}_FOUND AND NOT ${libless}_FOUND)
				set(hints ${hint_paths})
				if(WIN32)
					set(hints ${hint_paths} "C:/${libless}")
				endif()
				find_pkg(${libless})
				message("${libless}_FOUND: ${${libless}_FOUND}")
			endif()
		endif()
		if(NOT ${dep}_FOUND AND NOT ${libless}_FOUND)
			find_pkg(${dep} lib${dep})
			message("${dep}_FOUND: ${${dep}_FOUND}")
			if(NOT ${dep}_FOUND)
				message("lib${dep}_FOUND: ${lib${dep}_FOUND}")
			endif()
		endif()
	endforeach()
endmacro()

macro(dep_find_package)
	if(NOT ${ARGN} STREQUAL "")
		set(dep ${ARGN})
	endif()
	message("dep_find_package: searching for ${dep}")
	find_local_dep(${dep})
	if(NOT ${dep}_FOUND)
		string(REPLACE "-" "" dashless ${dep})
		string(REPLACE "-" "_" underscored ${dep})
		string(TOLOWER ${underscored} underscored_down)
		string(TOUPPER ${underscored} underscored_up)
		STRING(REGEX REPLACE "^LIB" "" libless_up ${underscored_up})
		STRING(REGEX REPLACE "^lib" "" libless_down ${underscored_down})
		if(NOT dashless STREQUAL dep)
			find_local_dep(${dashless})
			if(NOT ${dashless}_FOUND
				AND NOT dashless STREQUAL underscored
				)
				find_local_dep(${underscored})
				if(NOT ${underscored}_FOUND
					AND NOT underscored_down STREQUAL underscored
					)
					find_local_dep(${underscored_down})
					if(NOT ${underscored_down}_FOUND
						AND NOT dashless STREQUAL underscored_up
						)
						find_local_dep(${underscored_up})
						if(NOT ${underscored_up}_FOUND
							AND underscored_down MATCHES "^lib"
							)
							message("libless_up: ${libless_up}")
							find_local_dep(${libless_up})
							message("libless_up: ${libless_up}_FOUND: ${${libless_up}_FOUND}")
							if(NOT ${libless_up}_FOUND)
								message("libless_down: ${libless_down}")
								find_local_dep(${libless_down})
								message("libless_down: ${libless_down}_FOUND: ${${libless_down}_FOUND}")
							endif()
						endif()
					endif()
				endif()
			endif()
		endif()

		if(${dashless}_FOUND)
			message("dashless: ${dashless}_FOUND: ${${dashless}_FOUND}")
			set(dep ${dashless})
		elseif(${underscored}_FOUND)
			message("underscored: ${underscored}_FOUND: ${${underscored}_FOUND}")
			set(dep ${underscored})
		elseif(${underscored_up}_FOUND)
			message("underscored_up: ${underscored_up}_FOUND: ${${underscored_up}_FOUND}")
			set(dep ${underscored_up})
		elseif(${underscored_down}_FOUND)
			message("underscored_down: ${underscored_down}_FOUND: ${${underscored_down}_FOUND}")
			set(dep ${underscored_down})
		elseif(${libless_up}_FOUND)
			message("libless_up: ${libless_up}_FOUND: ${${libless_up}_FOUND}")
			set(dep ${libless_up})
		elseif(${libless_down}_FOUND)
			message("libless_down: ${libless_down}_FOUND: ${${libless_down}_FOUND}")
			set(dep ${libless_down})
		elseif(OPENMIND_USE_PKG_CONFIG_DEPS)
			message(STATUS "PKG_CONFIG_SYSROOT_DIR: $ENV{PKG_CONFIG_SYSROOT_DIR}")
			message(STATUS "PKG_CONFIG_PATH: $ENV{PKG_CONFIG_PATH}")
            message("pkg_check_modules(${underscored_down} IMPORTED_TARGET ${underscored_down}>=1.0)")
            pkg_check_modules(PKG IMPORTED_TARGET ${underscored_down}>=1.0)
			#message("pkg_search_module(${underscored_up} IMPORTED_TARGET ${underscored_down}>=1.0)")
			#pkg_search_module(${underscored_up} REQUIRED "${underscored_down}")
			message("PKG_FOUND: ${PKG_FOUND}")
			if(PKG_FOUND)
				message("PKG_CFLAGS: ${PKG_CFLAGS}")
				message("PKG_LIBRARIES: ${PKG_LIBRARIES}")
				pkg_check_modules(${underscored_down} IMPORTED_TARGET ${underscored_down}>=1.0)
				target_link_libraries(${this_target} PUBLIC PkgConfig::${underscored_down})
			else()
				message("Neither find_package nor pkg_config found ${dep}")
			endif()
			
		endif()
	endif()

	if(${dep}_FOUND)
		message("dep: ${dep}_FOUND: ${${dep}_FOUND}")
		message("dep: ${dep}_INCLUDE_DIR: ${${dep}_INCLUDE_DIR}")
		message("dep: ${dep}_INCLUDE_DIRS: ${${dep}_INCLUDE_DIRS}")
		message("dep: ${dep}_LIBRARY: ${${dep}_LIBRARY}")
		message("dep: ${dep}_LIBRARIES: ${${dep}_LIBRARIES}")
		if(this_target)
			if(${dep}_INCLUDE_DIR)
				message("${dep}_INCLUDE_DIR: ${${dep}_INCLUDE_DIR} for ${this_target}")
				target_include_directories(${this_target} PUBLIC ${${dep}_INCLUDE_DIR})
			endif()
			if(${dep}_INCLUDE_DIRS)
				message("${dep}_INCLUDE_DIRS: ${${dep}_INCLUDE_DIRS} for ${this_target}")
				target_include_directories(${this_target} PUBLIC ${${dep}_INCLUDE_DIRS})
			endif()
		endif()
		if(${dep}_LIBRARY)
			if(this_target)
				target_link_libraries(${this_target} PUBLIC ${${dep}_LIBRARY})
			endif()
		elseif(NOT ${dep}_LIBRARIES)
			find_library(${dep}_LIBRARIES NAMES ${dep} lib${dep} ${dep}lib lib${dep}lib)
		endif()
		message("${dep}_LIBRARIES: ${${dep}_LIBRARIES}")
		if(${dep}_LIBRARIES)
			foreach(lib ${${dep}_LIBRARIES})
				if(TARGET ${lib})
					set(repo SYSTEM)
					break()
				elseif(EXISTS "${lib}")
					set(repo SYSTEM)
					break()
				else()
					find_library(libfound ${lib})
					if(libfound)
						set(repo SYSTEM)
						break()	
					endif()
				endif()
				message("lib ${lib}")
			endforeach()
			if(repo)
				message("repo ${repo}")
				if(repo STREQUAL "SYSTEM")
					message("Found ${dep}_LIBRARIES: ${${dep}_LIBRARIES}")
					if(this_target)
						target_link_libraries(${this_target} PUBLIC ${${dep}_LIBRARIES})
					endif()
				else()
					message("Found no ${dep}_LIBRARIES: ${${dep}_LIBRARIES}")
					message("Trying external '${dep}' dependency from '${repo}'")
					ext(${dep} ${repo})
					if(OPENMIND_BUILD_BOOST)
						add_dependencies(${dep} boost)
					endif()
				endif()
			endif()
		endif()		
	else()
		message("No ${dep} local installations found")
	endif()
endmacro()

macro(find_optional_pkg)
	message("find local dep: ${ARGN}")
	string(REPLACE " " ";" ARGN ${ARGN})
	foreach(dep ${ARGN})
		if(NOT ${dep}_FOUND)
			if(DEFINED OPENMIND_USE_${dep})
				if(OPENMIND_USE_${dep})
					dep_find_package(${dep})
				endif()
			else()
				option(OPENMIND_USE_${dep} "Use ${dep}" ${${dep}_FOUND})
				dep_find_package(${dep})
				if(${dep}_FOUND)
					set(OPENMIND_USE_${dep} ON CACHE BOOL "Use ${dep}" FORCE)
				endif()
			endif()
			if(${dep}_FOUND)
				message("${dep}_FOUND: ${${dep}_FOUND}")
				message("${dep}_DIR: ${${dep}_DIR}")
			endif()
		endif()
	endforeach()
endmacro(find_optional_pkg)
