name: C/C++ CI Docker

on: []  # Workflow disabled

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ohhmm/openmind:latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv && which clang++) || (echo No dockerenv)

      - name: Install Dependencies
        run: |
          emerge-webrsync || exit 1
          emerge --getbinpkg=y --usepkg=y -q dev-libs/hiredis dev-util/pkgconfig dev-util/ninja dev-util/cmake dev-cpp/boost dev-util/ccache || exit 1

      - name: Setup ccache
        run: |
          ccache --max-size=2G
          ccache --zero-stats

      - name: Create Build Dir
        run: cmake -E make_directory ./build

      - name: Configure
        working-directory: ./build
        env:
          CC: ccache /usr/lib/llvm/17/bin/clang-17
          CXX: ccache /usr/lib/llvm/17/bin/clang++-17
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_COMPILER=/usr/lib/llvm/17/bin/clang-17 -DCMAKE_C_COMPILER=/usr/lib/llvm/17/bin/clang-17 \
          -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON -DOPENMIND_STORAGE_REDIS=ON -DBOOST_TEST_NO_AUTO_LINK=ON -DBoost_USE_STATIC_LIBS=ON

      - name: Install prerequisites
        working-directory: ./build
        run: cmake --build . --target prerequisites -j `nproc`

      - name: Reconfigure to detect prerequisites
        working-directory: ./build
        run: cmake .

      - name: Build
        run: cmake --build build -j$(nproc) --verbose

      - name: Check
        working-directory: ./build
        run: ctest . -j`nproc` -E ts --rerun-failed --output-on-failure
