name: Create Issue on Workflow Failure

on:
  workflow_run:
    workflows: ['*']
    types:
      - completed

jobs:
  create-issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Workflow Failure: ${context.payload.workflow_run.name}`,
              body: `The workflow **${context.payload.workflow_run.name}** failed. Please investigate.\n\n[View the failed workflow run](${context.payload.workflow_run.html_url})`,
              labels: ["automation", "devin"]
            });
            console.log(`Created issue: ${issue.html_url}`);