name: C/C++ CI Docker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ohhmm/openmind:latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv && which clang++) || (echo No dockerenv)

      - name: Install Dependencies
        run: |
          emerge --sync
          emerge -q dev-libs/hiredis dev-util/pkgconfig

      - name: Create Build Dir
        run: cmake -E make_directory ./build

      - name: Configure
        working-directory: ./build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_COMPILER=/usr/lib/llvm/17/bin/clang-17 -DCMAKE_C_COMPILER=/usr/lib/llvm/17/bin/clang-17 \
          -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_STORAGE_REDIS=ON

      # - name: Install prerequisites
      #   working-directory: ./build
      #   run: cmake --build . --target prerequisites -j `nproc`

      # - name: Reconfigure to detect newly installed prerequisites
      #   working-directory: ./build
      #   run: cmake .

      - name: Build
        run: cmake --build build

      - name: Check
        working-directory: ./build
        run: ctest . -j`nproc` -E ts --rerun-failed --output-on-failure
