name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ohhmm/openmind:latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Debug -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON -G Ninja
    - name: make
      run: cmake --build . 
    - name: make check
      run: ctest . -j`nproc` 
