name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ohhmm/openmind:latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake ${{github.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=Debug -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON
      - name: Install prerequisites
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --target prerequisites -j `sysctl -n hw.ncpu`
      - name: Reconfigure to detect newly installed prerequisites
        working-directory: ${{github.workspace}}/build
        run: cmake .

      - name: Build
        run: cmake --build . 
      - name: Check
        run: ctest . -j`nproc` 
