name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ohhmm/openmind:latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv && which clang++) || (echo No dockerenv)

      - name: Create Build Dir
        run: cmake -E make_directory ./build

      - name: Configure
        working-directory: ./build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_COMPILER=/usr/lib/llvm/18/bin/clang-18 -DCMAKE_C_COMPILER=/usr/lib/llvm/18/bin/clang-18 \
          -DOPENMIND_BUILD_SAMPLES=OFF

      - name: Install prerequisites
        working-directory: ./build
        run: cmake --build . --target prerequisites -j `nproc`

      - name: Reconfigure to detect newly installed prerequisites
        working-directory: ./build
        run: cmake .

      - name: Build
        run: cmake --build build

      - name: Check
        working-directory: ./build
        run: ctest . -j`nproc` Product_test.*\|Sum_test.*\|MultiValues_test.*\|Exponentiation_test.*\|image_codec_test.*\|test_extrapolator.*\|sh_test.*\|ts.*\|Polyfit_test.*

