name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: docker://ohhmm/openmind
    - uses: actions/checkout@v1
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
