name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ohhmm/openmind:latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Create Build Dir
        run: cmake -E make_directory ./build

      - name: Configure
        working-directory: ./build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON

      - name: Install prerequisites
        working-directory: ./build
        run: cmake --build . --target prerequisites -j `nproc`

      - name: Reconfigure to detect newly installed prerequisites
        working-directory: ./build
        run: cmake .

      - name: Build
        run: cmake --build build

      - name: Check
        working-directory: ./build
        run: ctest . -j`nproc`
