name: Build Maintain Target After Main

on:
  workflow_run:
    workflows: ["C/C++ CI Ubuntu", "C/C++ CI MSVC", "C/C++ CI macOS"]
    branches: [main]
    types:
      - completed

jobs:
  build-maintain:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt
          /var/lib/apt/lists
          ${{ github.workspace }}/build/bin/Db*.solutions
        key: ${{ runner.os }}-apt-${{ hashFiles('**/ubuntu.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-
    
    - name: OS prerequisites
      run: sudo add-apt-repository -y ppa:mhier/libboost-latest && sudo apt update && sudo apt upgrade -y && sudo apt install -y libboost1.83-all-dev libxss-dev libx11-dev libxcb-screensaver0-dev ocl-icd-opencl-dev libopengl-dev freeglut3-dev libleveldb-dev libsnappy-dev libvulkan-dev liblz4-dev libfmt-dev librocksdb-dev libpython3-all-dev libopencl-clang-dev libtbb-dev ninja-build
    
    - name: Create Build Dir
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON -DOPENMIND_USE_OPENCL=OFF -G "Ninja Multi-Config"
    
    - name: Build maintain target
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --target origin-remote-maintain -j `nproc` --config Release
