name: C/C++ CI MSVC

on: [push]

jobs:
  build:
    runs-on: windows-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install
        .\vcpkg\vcpkg install hiredis:x64-windows

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: |
        cmake .. -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DOPENMIND_BUILD_SAMPLES=OFF `
          -DOPENMIND_STORAGE_REDIS=ON `
          -DOPENMIND_USE_VCPKG=ON

    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release

    - name: Test
      working-directory: ./build
      run: ctest -C Release -j 4 -E "(ts|image_codec_test)" --rerun-failed --output-on-failure
