name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt install -y libboost-all-dev libxss-dev libx11-dev libxcb-screensaver0-dev ocl-icd-opencl-dev libopengl-dev freeglut3-dev libleveldb-dev libvulkan-dev liblz4-dev libfmt-dev librocksdb-dev libpython3-all-dev libopencl-clang-dev libtbb-dev
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
