name: C/C++ CI

on: [push]

jobs:
  build-in-ubuntu:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: OS prerequisites
      run: |
        sudo apt update &&
        sudo apt install -y libxss-dev libx11-dev libxcb-screensaver0-dev ocl-icd-opencl-dev libopengl-dev freeglut3-dev libleveldb-dev libsnappy-dev libvulkan-dev liblz4-dev libfmt-dev librocksdb-dev libpython3-all-dev libopencl-clang-dev libtbb-dev ninja-build
    # Boost is now built from source, installation from package manager is not required
    # - name: Install Boost
    #   run: |
    #     sudo apt-get install -y libboost1.85-dev libboost-filesystem1.85-dev libboost-thread1.85-dev libboost-system1.85-dev libboost-date-time1.85-dev libboost-serialization1.85-dev libboost-regex1.85-dev
    - name: Create Build Dir
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON -DOPENMIND_USE_OPENCL=OFF -G "Ninja Multi-Config"
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build -j `nproc` --config Release
    - name: Check
      working-directory: ${{github.workspace}}/build
      run: ctest . -j`nproc` -C Release -E "image_codec_test|ts|Polyfit_test" --rerun-failed --output-on-failure
