name: C/C++ CI

on: [push]

jobs:
  build-in-ubuntu:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Create Build Dir
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: prerequisites
      run: sudo apt install -y libboost-all-dev libxss-dev libx11-dev libxcb-screensaver0-dev ocl-icd-opencl-dev libopengl-dev freeglut3-dev libleveldb-dev libvulkan-dev liblz4-dev libfmt-dev librocksdb-dev libpython3-all-dev libopencl-clang-dev libtbb-dev ninja-build
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Debug -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON -DOPENMIND_REQUIRED_BOOST_VERSION="" -G Ninja
    - name: Install prerequisites
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --target prerequisites -j `nproc`
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build -j `nproc`
    - name: Check
      working-directory: ${{github.workspace}}/build
      run: ctest --timeout 120 -C Debug -j `nproc`
