name: C/C++ CI

on: [push]

jobs:
  build-on-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Create Build Dir
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Debug -DOPENMIND_BUILD_SAMPLES=OFF -DOPENMIND_BUILD_TESTS=ON -G Ninja
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build
    - name: make check
      working-directory: ${{github.workspace}}/build
      run: ctest --timeout 120 -C Debug -j %NUMBER_OF_PROCESSORS%
