name: C/C++ CI MSVC

on: [push]

jobs:
  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Cache Boost dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/build/CMakeFiles
          C:/Boost
          ${{ github.workspace }}/build/bin/Db*.solutions
        key: ${{ runner.os }}-boost-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-boost-
    - name: Create Build Dir
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Install vcpkg
      shell: pwsh
      run: |
        git clone https://github.com/Microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
        cd ${{ github.workspace }}/vcpkg
        git fetch origin
        git checkout 96dbba1e03d1ecc7c7096e97d5a09ff3c58e21df
        git pull origin 96dbba1e03d1ecc7c7096e97d5a09ff3c58e21df
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install boost-test:x64-windows boost-filesystem:x64-windows boost-system:x64-windows boost-thread:x64-windows boost-program-options:x64-windows boost-serialization:x64-windows boost-chrono:x64-windows boost-date-time:x64-windows boost-iostreams:x64-windows boost-locale:x64-windows boost-atomic:x64-windows leveldb:x64-windows opencl:x64-windows
        
    - name: Set environment variables
      shell: pwsh
      run: |
        "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $env:GITHUB_ENV
        "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV
        "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $env:GITHUB_ENV
        "VCPKG_INSTALLED_DIR=${{ github.workspace }}/vcpkg/installed" >> $env:GITHUB_ENV

    - name: Configure
      working-directory: ${{github.workspace}}/build
      env:
        CC: cl
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        VCPKG_DEFAULT_TRIPLET: x64-windows
        CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      run: |
        cmake ${{github.workspace}} `
          -DCMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE }} `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -DCMAKE_BUILD_TYPE=Release `
          -DOPENMIND_USE_VCPKG=ON `
          -DOPENMIND_USE_CONAN=OFF `
          -DOPENMIND_BUILD_SAMPLES=OFF `
          -DOPENMIND_BUILD_TESTS=ON `
          -G "Ninja Multi-Config" `
          -DCMAKE_C_COMPILER="cl.exe" `
          -DCMAKE_CXX_COMPILER="cl.exe" `
          -DCMAKE_PREFIX_PATH=${{ env.VCPKG_ROOT }}/installed/x64-windows `
          -DVCPKG_INSTALLED_DIR=${{ env.VCPKG_ROOT }}/installed `
          -Dleveldb_TAG:STRING="1.23" `
          -DOPENMIND_MATH_USE_LEVELDB_CACHE=NO `
          -DOPENMIND_STORAGE_LEVELDB=NO

    - name: Install prerequisites
      run: cmake --build ${{github.workspace}}/build --target prerequisites --config Release

    - name: Reconfigure to detect newly installed prerequisites
      working-directory: ${{github.workspace}}/build
      run: cmake .

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - name: Build Debug
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Build Release
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: make check Release
      working-directory: ${{github.workspace}}/build
      run: ctest --timeout 2048 -C Release -j ${{steps.cpu-cores.outputs.count}}  -E "ts"  --output-on-failure
            #   --rerun-failed --output-on-failure

    - name: make check Debug
      working-directory: ${{github.workspace}}/build
      run: ctest --timeout 2048 -C Debug -j ${{steps.cpu-cores.outputs.count}}  -E "ts" --output-on-failure
            #   --rerun-failed --output-on-failure

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --target install --config Release
